import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { TopScrollBlur } from "@/components/top-scroll-blur";
// import { Dock } from "@/components/ui/dock";
import { NewDock } from "@/components/ui/new-dock";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${inter.variable} h-full antialiased`}
    >
      <body  className="min-h-full flex flex-col pb-16 sm:pb-20">
        <TopScrollBlur />
        {children}
        {/* <Dock /> */}
        <NewDock />
      </body>
    </html>
  );
}
