import type { Metadata } from "next";
import Script from "next/script";
import { Inter } from "next/font/google";
import "./globals.css";
import { TopScrollBlur } from "@/components/top-scroll-blur";
// import { Dock } from "@/components/ui/dock";
import { NewDock } from "@/components/ui/new-dock";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Resolves night mode before the browser paints.
 *
 * The server can't read `localStorage`, so it always emits the light document.
 * This runs synchronously while `<head>` is parsed — earlier than any effect
 * could — so the page never flashes light on its way to dark. Must stay in sync
 * with `resolveTheme` in `lib/use-theme.ts`, which the dock's switch reads.
 */
const THEME_BOOT_SCRIPT = `(function(){try{var s=localStorage.getItem("theme");var d=s==="dark"||(s!=="light"&&window.matchMedia("(prefers-color-scheme: dark)").matches);document.documentElement.classList.toggle("dark",d)}catch(e){}})()`;

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${inter.variable} h-full antialiased`}
    >
      <head>
        <Script id="theme-boot" strategy="beforeInteractive" dangerouslySetInnerHTML={{ __html: THEME_BOOT_SCRIPT }} />
      </head>
      <body  className="min-h-full flex flex-col pb-16 sm:pb-20">
        <TopScrollBlur />
        {children}
        {/* <Dock /> */}
        <NewDock />
      </body>
    </html>
  );
}
